export default typeof defineAppConfig === 'function'
  ? defineAppConfig({
    pages: [
      'pages/index/index',
      'pages/login/index',
      'pages/role-select/index',
      'pages/records/index',
      'pages/messages/index',
      'pages/profile/index',
      'pages/pickup/index',
      'pages/growth/index',
      'pages/roll-call/index',
      'pages/class-detail/index',
      'pages/binding/index',
      'pages/review/index',
      'pages/teacher-manage/index',
      'pages/teacher-notification/index',
      'pages/admin/class-manage/index',
      'pages/admin/class-edit/index',
      'pages/admin/children/index',
      'pages/admin/teacher-manage/index',
      'pages/admin/teacher-edit/index',
      'pages/admin/notification-manage/index',
      'pages/admin/notification-edit/index',
      'pages/admin/child-detail/index',
      'pages/admin/child-edit/index',
      'pages/admin/child-add/index',
      'pages/child-setting/index',
    ],
    tabBar: {
      color: '#999999',
      selectedColor: '#E8651A',
      backgroundColor: '#ffffff',
      borderStyle: 'white',
      list: [
        {
          pagePath: 'pages/index/index',
          text: '首页',
          iconPath: './assets/tabbar/house.png',
          selectedIconPath: './assets/tabbar/house-active.png',
        },
        {
          pagePath: 'pages/records/index',
          text: '记录',
          iconPath: './assets/tabbar/clipboard-list.png',
          selectedIconPath: './assets/tabbar/clipboard-list-active.png',
        },
        {
          pagePath: 'pages/messages/index',
          text: '消息',
          iconPath: './assets/tabbar/bell.png',
          selectedIconPath: './assets/tabbar/bell-active.png',
        },
        {
          pagePath: 'pages/profile/index',
          text: '我的',
          iconPath: './assets/tabbar/user.png',
          selectedIconPath: './assets/tabbar/user-active.png',
        },
      ],
    },
    window: {
      backgroundTextStyle: 'light',
      navigationBarBackgroundColor: '#E8651A',
      navigationBarTitleText: '力高稚家',
      navigationBarTextStyle: 'white'
    }
  })
  : {
    pages: [
      'pages/index/index',
      'pages/login/index',
      'pages/role-select/index',
      'pages/records/index',
      'pages/messages/index',
      'pages/profile/index',
      'pages/pickup/index',
      'pages/growth/index',
      'pages/roll-call/index',
      'pages/class-detail/index',
      'pages/binding/index',
      'pages/review/index',
      'pages/teacher-manage/index',
      'pages/teacher-notification/index',
      'pages/admin/class-manage/index',
      'pages/admin/class-edit/index',
      'pages/admin/children/index',
      'pages/admin/teacher-manage/index',
      'pages/admin/notification-manage/index',
      'pages/admin/notification-edit/index',
    ],
    tabBar: {
      color: '#999999',
      selectedColor: '#E8651A',
      backgroundColor: '#ffffff',
      borderStyle: 'white',
      list: [
        {
          pagePath: 'pages/index/index',
          text: '首页',
          iconPath: './assets/tabbar/house.png',
          selectedIconPath: './assets/tabbar/house-active.png',
        },
        {
          pagePath: 'pages/records/index',
          text: '记录',
          iconPath: './assets/tabbar/clipboard-list.png',
          selectedIconPath: './assets/tabbar/clipboard-list-active.png',
        },
        {
          pagePath: 'pages/messages/index',
          text: '消息',
          iconPath: './assets/tabbar/bell.png',
          selectedIconPath: './assets/tabbar/bell-active.png',
        },
        {
          pagePath: 'pages/profile/index',
          text: '我的',
          iconPath: './assets/tabbar/user.png',
          selectedIconPath: './assets/tabbar/user-active.png',
        },
      ],
    },
    window: {
      backgroundTextStyle: 'light',
      navigationBarBackgroundColor: '#E8651A',
      navigationBarTitleText: '力高稚家',
      navigationBarTextStyle: 'white'
    }
  }
